package com.example.caredirectiontest.utils;

public class ResponseMessage {
    public static final String NULL_VALUE = "필요한 값이 없습니다.";
    public static final String INVALID_TOKEN ="유효하지 않은 token 입니다.";
    public static final String EMPTY_TOKEN = "토큰값이 존재하지 않습니다.";
    public static final String EXPIRED_TOKEN = "만료된 토큰입니다.";
    public static final String EMPTY_REFRESH_TOKEN = "재발급 토큰이 존재하지 않습니다.";
    public static final String CREATE_TOKEN = "토큰 발급 완료.";
    public static final String REFRESH_TOKEN = "토큰 재발급 완료.";
    public static final String NO_SELECT_AUTHORITY = "조회 권한 없음.";
    public static final String USER_SELECTED = "회원 조회 성공.";
    public static final String PRODUCT_INSERT_SUCCESS = "제품 등록 성공";
    public static final String SIGN_UP_INSERT_SUCCESS = "회원가입 성공";
    public static final String SIGN_IN_SUCCESS = "로그인 성공";
    public static final String SIGN_IN_ERROR = "잘못된 아이디 또는 비밀번호 입니다.";
    public static final String VALID_ID = "이용가능한 아이디";
    public static final String INVALID_ID = "중복되는 아이디";
    public static final String MODIFY_SUCCESS = "닉네임 수정 완료";
    public static final String MODIFY_FAILED = "닉네임 수정 실패";
    public static final String SURVEY_INFO_SUCCESS = "개인정보 설문조사 성공";
    public static final String SURVEY_INFO_FAILED = "개인정보 설문조사 실패";
    public static final String SURVEY_LIFECYCLE_SUCCESS = "라이프사이클 설문조사 성공";
    public static final String SURVEY_LIFECYCLE_FAILED = "라이프사이클 설문조사 실패";
    public static final String EFFICACY_INSERT_SUCCESS = "효능 등록 성공";
    public static final String NUTRIENT_INSERT_SUCCESS = "성분 등록 성공";
    public static final String INSERT_FAILED = "등록 실패";
    public static final String PRODUCT_DOSE_INSERT_SUCCESS = "복용 등록 성공";
    public static final String PRODUCT_DOSE_MODIFY_SUCCESS = "복용 수정 성공";
    public static final String PRODUCT_DOSE_DELETE_SUCCESS = "복용 취소 성공";
    public static final String PRODUCT_DOSE_DELETE_FAIL = "복용 취소 실패";
    public static final String PRODUCT_DOSE_INSERT_DUPLICATED = "이미 복용 등록되었습니다.";
    public static final String INTERNAL_SERVER_ERROR = "서버 내부 에러";
    public static final String SUCCESS = "success";
    public static final String DUPLICATED = "duplicated";
    public static final String EFFICACY_SELECTED = "효능 리스트 조회 성공";
    public static final String MY_EFFICACY_SUCCESS = "내가 영향 받고있는 효능 리스트 조회 성공";
    public static final String DB_ERROR = "데이터베이스 에러";
    public static final String USER_LIST_GET_SUCCESS = "유저 관리 리스트 가져오기 성공";
    public static final String USER_LIST_GET_FAIL = "유저 관리 리스트 가져오기 실패";
    public static final String SELECT_SUCCESS = "조회 성공";
    public static final String REMOVE_CHILD_USER_SUCCESS = "child 사용자 삭제 성공";
    public static final String REMOVE_CHILD_USER_FAIL = "child 사용자 삭제 실패";
    public static final String DOSE_PRODUCT_DELETE_SUCCESS = "복용 제품 삭제 성공";
    public static final String DOSE_PRODUCT_DELETE_FAIL = "복용 제품 삭제 실패";
    public static final String DOSE_PRODUCT_POPUP_SUCCESS = "복용 제품 팝업 메시지 성공";
    public static final String MY_CARE_FUNCTIONAL_NUTRIENTS_SUCCESS = "기능 성분 가져오기 성공";
    public static final String MY_CARE_FUNCTIONAL_NUTRIENTS_FAIL = "기능 성분 가져오기 실패";
    public static final String GET_NUTRIENT_INFO_SUCCESS = "특정 성분 정보 가져오기 성공";
    public static final String GET_PRODUCT_DETAIL_INFO_SUCCESS = "제품 상세 정보 가져오기 성공";
    public static final String LOWEST_PRICE_SUCCESS = "최저가 정보 성공";
    public static final String SEARCH_SUCCESS = "검색 성공";
    public static final String SEARCH_DATA_EMPTY = "검색 결과가 없습니다.";
    public static final String GET_PRODUCT_DETAIL_EFFICACY_SUCCESS = "제품 디테일 효능 성공";
    public static final String USER_CUSTOM_PRODUCT_TABLIST = "상품 탭 리스트 성공";
    public static final String GET_PRODUCT_DETAIL_GRAPH_SUCCESS = "제품 상세 그래프 성공";
    public static final String ARTICLE_DATA_LIST = "아티클 리스트 가져오기 성공";
    public static final String ARTICLE_DATA_SUCCESS = "아티클 리스트 가져오기 성공";
    public static final String VALUE_MUST_INTEGER = "정수 값을 보내야 합니다";


}
